#!/usr/bin/env bash
source scripts/env_debug_round_tclean_selector.sh

export DEBUG_TARGET_LEAKAGE_CHECK=0

# 只训 selector
export TRAIN_SELECTOR_ONLY_STAGE=1

# topK 改小
export SELECTOR_TOPK=64
export MODEL_TOPK_EVAL=64
export TARGET_SUPPORT_TOPK=64
export TEACHER_TOPK_TRAIN=128
export TEACHER_TOPK_EVAL=128

# 先不让 fragment aux 太强
export FRAGMENT_LOCAL_AUX_SCALE=0.5

# 所有后续头先关
export RERANK_LOSS_WEIGHT=0.0
export MAIN_CANDIDATE_KL_WEIGHT=0.0
export OFFICIAL_SPECTRAL_LOSS_WEIGHT=0.0
export OFFICIAL_SPECTRAL_KL_WEIGHT=0.0
export FALSE_SUPPORT_LOSS_WEIGHT=0.0
export PEAK_AUX_LOSS_WEIGHT=0.0
export OOS_LOSS_WEIGHT=0.0
export PRECURSOR_LOSS_WEIGHT=0.0
export COARSE_SPECTRAL_AUX_WEIGHT=0.0

export FORMULA_RENDER_TOPK=0
export FORMULA_RENDER_TOPK_TRAIN=0

export BATCH_SIZE=4
export NUM_WORKERS=0
export EPOCHS=2
export MAX_TRAIN_STEPS=500
export MAX_VAL_STEPS=100

export MODEL_SELECT_METRIC=selector_precision_at_64