#!/usr/bin/env bash
cd /home/lwh/projects/lrq2/ms1

export FEAT_CACHE_DIR_TRAIN=/home/lwh/projects/lrq2/ms1/data/nist_20/cache_train3000_v3c_balanced_recursive_fragment_node
export FEAT_CACHE_DIR_VAL=/home/lwh/projects/lrq2/ms1/data/nist_20/cache_val1000_v3c_balanced_recursive_fragment_node

# 如果你平时训练需要 TRAIN_PARQUET / VAL_PARQUET，就保留你原来那两个；
# 如果 train_ms_subsetnet.py 里已经写死默认路径，这里可以不设。
# export TRAIN_PARQUET=...
# export VAL_PARQUET=...

export FORMULA_ATOMICNOS=1,6,7,8,9,15,16,17,35,53,11
unset FORMULA_OH_SIZES
unset LOAD_MODEL_PATH

export EVAL_USE_TEACHER_TOPK=0
export USE_TEACHER_FORMULA_TARGET=1
export TEACHER_TOPK_MASK_POSITIVE_ONLY=1

export OFFICIAL_BIN_WIDTH=0.01
export OFFICIAL_MAX_MZ=1005.0
export OFFICIAL_EXCLUDE_PRECURSOR=1
export OFFICIAL_SPECTRAL_LOSS_MODE=cos

export BATCH_SIZE=4
export EPOCHS=6
export LR=1e-4
export NUM_WORKERS=4
export MAX_TRAIN_STEPS=0
export MAX_VAL_STEPS=0
export MODEL_SELECT_METRIC=official_cos

export QUALITY_USE_SETCOVER_TEACHER=1
export QUALITY_SETCOVER_POOL_TOPK=1024
export QUALITY_SETCOVER_TOPK=24
export QUALITY_SETCOVER_LAMBDA_FALSE=0.25
export QUALITY_SETCOVER_LAMBDA_REDUN=0.10
export QUALITY_SETCOVER_HYBRID=1
export QUALITY_SETCOVER_HYBRID_Q6_WEIGHT=0.8
export QUALITY_TARGET_GAMMA=2.0

export SELECTOR_TOPK=256
export MODEL_TOPK_EVAL=256
export TEACHER_TOPK_TRAIN=256
export TEACHER_TOPK_EVAL=512
export TARGET_SUPPORT_TOPK=256

export SELECTOR_LOSS_WEIGHT=1.0
export SELECTOR_BCE_WEIGHT=0.30
export SELECTOR_KL_WEIGHT=0.70
export SELECTOR_POS_WEIGHT=3.0
export SELECTOR_BALANCED_BCE=1
export SELECTOR_BALANCED_POS_PART=0.7

export ENABLE_SELECTOR_PAIRWISE=0
export SELECTOR_PAIRWISE_WEIGHT=0.0

export MAIN_CANDIDATE_KL_WEIGHT=0.0
export OFFICIAL_SPECTRAL_LOSS_WEIGHT=0.0
export OFFICIAL_SPECTRAL_KL_WEIGHT=0.0
export FALSE_SUPPORT_LOSS_WEIGHT=0.0
export PEAK_AUX_LOSS_WEIGHT=0.0
export USE_REFINED_PEAK_RENDER=0
export OOS_LOSS_WEIGHT=0.0
export PRECURSOR_LOSS_WEIGHT=0.0
export COARSE_SPECTRAL_AUX_WEIGHT=0.0

export FORMULA_RENDER_TOPK=20
export FORMULA_RENDER_TOPK_TRAIN=0
export FORMULA_SCORE_TEMPERATURE=0.70
export FORMULA_SCORE_SCALE=1.0
export FORMULA_ENTROPY_LOSS_WEIGHT=0.0
export DEBUG_RENDER_TOPK=0
export MODEL_TOPK_USE_ACTIVE_MASK=0
export USE_FN_FORMULA_LOGITS_AS_SELECTOR=0