#!/usr/bin/env bash
source scripts/clean_lrq_env.sh

PROJECT_ROOT="${PROJECT_ROOT:-$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)}"
cd "$PROJECT_ROOT"

export FEAT_CACHE_DIR_TRAIN="${FEAT_CACHE_DIR_TRAIN:-$PROJECT_ROOT/data/nist_20/cache_train}"
export FEAT_CACHE_DIR_VAL="${FEAT_CACHE_DIR_VAL:-$PROJECT_ROOT/data/nist_20/cache_val}"

# 如果你有 Stage1 best，就在运行前自己指定
# export LOAD_MODEL_PATH=/path/to/stage1_best.pth

export FORMULA_ATOMICNOS=1,6,7,8,9,15,16,17,35,53,11

export MODEL_ALLOW_TARGET_ALIGNMENT_FEAT=0
export STRICT_MODEL_KWARG_WHITELIST=1
export DEBUG_TARGET_LEAKAGE_CHECK=1

export USE_COVERAGE_AWARE_TOPK=0
export USE_FN_FORMULA_LOGITS_AS_SELECTOR=0

export SELECTOR_TOPK=8
export MODEL_TOPK_EVAL=8
export TARGET_SUPPORT_TOPK=64

export MODEL_SELECT_METRIC=official_cos_no_precursor
export MODEL_SELECT_MODE=max

export SELECTOR_LOSS_WEIGHT=0.50
export SELECTOR_BCE_WEIGHT=0.10
export SELECTOR_KL_WEIGHT=0.05
export SELECTOR_RECALL_BCE_WEIGHT=0.10
export SELECTOR_PAIRWISE_WEIGHT=0.10
export SELECTOR_UTILITY_LOSS_WEIGHT=0.25
export FALSE_SUPPORT_LOSS_WEIGHT=0.20
export SELECTOR_POS_WEIGHT=5.0

export OFFICIAL_SPECTRAL_LOSS_WEIGHT=0.20
export OFFICIAL_DENSE_KL_WEIGHT=0.05
export OFFICIAL_DENSE_FALSE_WEIGHT=0.00
export OFFICIAL_SPECTRAL_LOSS_MODE=cos

export RERANK_LOSS_WEIGHT=0.00
export PEAK_LOSS_WEIGHT=0.00
export OOS_LOSS_WEIGHT=0.00
export PRECURSOR_LOSS_WEIGHT=0.00

export FORMULA_RENDER_TOPK=8
export FORMULA_RENDER_TOPK_TRAIN=1

export BATCH_SIZE=4
export EPOCHS=30
export LR=8e-5
export NUM_WORKERS=4