#!/usr/bin/env bash
source scripts/clean_lrq_env.sh

PROJECT_ROOT="${PROJECT_ROOT:-$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)}"
cd "$PROJECT_ROOT"

export USE_CLEAN_ENGINE=1

export FEAT_CACHE_DIR_TRAIN="${FEAT_CACHE_DIR_TRAIN:-$PROJECT_ROOT/data/nist_20/cache_train}"
export FEAT_CACHE_DIR_VAL="${FEAT_CACHE_DIR_VAL:-$PROJECT_ROOT/data/nist_20/cache_val}"

export FORMULA_ATOMICNOS=1,6,7,8,9,15,16,17,35,53,11

export USE_FRAGMENT_LOCAL_AUX=1
export GATE_FRAGMENT_LOCAL_AUX=1
export FRAGMENT_LOCAL_AUX_SCALE=1.0
export FRAG_AUX_MAX_DEPTH=2

export MODEL_ALLOW_TARGET_ALIGNMENT_FEAT=0
export STRICT_MODEL_KWARG_WHITELIST=1
export DEBUG_TARGET_LEAKAGE_CHECK=1

export USE_FN_FORMULA_LOGITS_AS_SELECTOR=0
export MODEL_TOPK_USE_ACTIVE_MASK=0

export SELECTOR_TOPK=8
export MODEL_TOPK_EVAL=8
export TARGET_SUPPORT_TOPK=64

export SELECTOR_LOSS_WEIGHT=1.0
export SELECTOR_BCE_WEIGHT=0.30
export SELECTOR_KL_WEIGHT=0.20
export SELECTOR_RECALL_BCE_WEIGHT=0.20
export SELECTOR_PAIRWISE_WEIGHT=0.20
export SELECTOR_UTILITY_LOSS_WEIGHT=0.50
export FALSE_SUPPORT_LOSS_WEIGHT=0.20
export SELECTOR_POS_WEIGHT=5.0

export RERANK_LOSS_WEIGHT=0.0
export OFFICIAL_SPECTRAL_LOSS_WEIGHT=0.0
export OFFICIAL_DENSE_KL_WEIGHT=0.0
export OFFICIAL_DENSE_FALSE_WEIGHT=0.0
export PEAK_LOSS_WEIGHT=0.0
export OOS_LOSS_WEIGHT=0.0
export PRECURSOR_LOSS_WEIGHT=0.0

export FORMULA_RENDER_TOPK=0
export FORMULA_RENDER_TOPK_TRAIN=0

export BATCH_SIZE=4
export EPOCHS=8
export LR=1e-4
export NUM_WORKERS=4

export MODEL_SELECT_METRIC=selected_false_mass@8
export MODEL_SELECT_MODE=min
export BEST_CKPT_PATH=checkpoints/stage1_top8_selector_best.pt