#!/usr/bin/env bash
source scripts/clean_lrq_env.sh

PROJECT_ROOT="${PROJECT_ROOT:-$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)}"
cd "$PROJECT_ROOT"

export USE_CLEAN_ENGINE=1

export FEAT_CACHE_DIR_TRAIN="${FEAT_CACHE_DIR_TRAIN:-$PROJECT_ROOT/data/nist_20/cache_train}"
export FEAT_CACHE_DIR_VAL="${FEAT_CACHE_DIR_VAL:-$PROJECT_ROOT/data/nist_20/cache_val}"

# 改成你的 stage1 best
export LOAD_MODEL_PATH="${LOAD_MODEL_PATH:-checkpoints/stage1_top8_selector_best.pt}"

export FORMULA_ATOMICNOS=1,6,7,8,9,15,16,17,35,53,11

export MODEL_ALLOW_TARGET_ALIGNMENT_FEAT=0
export STRICT_MODEL_KWARG_WHITELIST=1
export DEBUG_TARGET_LEAKAGE_CHECK=1

export USE_FN_FORMULA_LOGITS_AS_SELECTOR=0
export MODEL_TOPK_USE_ACTIVE_MASK=0

export SELECTOR_TOPK=8
export MODEL_TOPK_EVAL=8
export TARGET_SUPPORT_TOPK=64

export SELECTOR_LOSS_WEIGHT=0.30
export SELECTOR_BCE_WEIGHT=0.10
export SELECTOR_KL_WEIGHT=0.05
export SELECTOR_RECALL_BCE_WEIGHT=0.10
export SELECTOR_PAIRWISE_WEIGHT=0.10
export SELECTOR_UTILITY_LOSS_WEIGHT=0.20
export FALSE_SUPPORT_LOSS_WEIGHT=0.10
export SELECTOR_POS_WEIGHT=5.0

export RERANK_LOSS_WEIGHT=0.0

export OFFICIAL_SPECTRAL_LOSS_WEIGHT=0.20
export OFFICIAL_DENSE_KL_WEIGHT=0.05
export OFFICIAL_DENSE_FALSE_WEIGHT=0.00
export OFFICIAL_SPECTRAL_LOSS_MODE=cos

export PEAK_LOSS_WEIGHT=0.0
export OOS_LOSS_WEIGHT=0.0
export PRECURSOR_LOSS_WEIGHT=0.0

export FORMULA_RENDER_TOPK=8
export FORMULA_RENDER_TOPK_TRAIN=1

export BATCH_SIZE=4
export EPOCHS=30
export LR=8e-5
export NUM_WORKERS=4

export MODEL_SELECT_METRIC=official_cos_no_precursor
export MODEL_SELECT_MODE=max
export BEST_CKPT_PATH=checkpoints/stage2_top8_spectral_best.pt

export SELECTOR_ONLY_WARMUP_EPOCHS=0
export SPECTRAL_LOSS_START_EPOCH=0
export PEAK_AUX_START_EPOCH=9999
export OOS_LOSS_START_EPOCH=9999